/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-2',
  aws_cognito_identity_pool_id:
    'eu-west-2:5aaabba7-186c-4db3-bbea-d4bf45b90362',
  aws_cognito_region: 'eu-west-2',
  aws_user_pools_id: 'eu-west-2_dFrTb0myg',
  aws_user_pools_web_client_id: '3ue6qkn540c9n7j0042onurd1k',
  oauth: {
    domain: 'xaiapp694473c6-694473c6-dev.auth.eu-west-2.amazoncognito.com',
    scope: [
      'phone',
      'email',
      'openid',
      'profile',
      'aws.cognito.signin.user.admin',
    ],
    redirectSignIn: 'http://localhost:4200/',
    redirectSignOut: 'http://localhost:4200/',
    responseType: 'code',
  },
  federationTarget: 'COGNITO_USER_POOLS',
};

export default awsmobile;
